Update Downloads Page
shapiromatron/hawc pull request #1067
Opened 2024-07-11 22:37 UTC by caseyhans

Reference downloads page UI and add UDF downloads

<details><summary>Before</summary>
<p>

- Too bulky; card columns wasted space and pushed downloads below of page. 
![image](https://github.com/user-attachments/assets/a851a61a-144e-4f76-983e-bd8db0864407)

</p>
</details> 

<details><summary>After</summary>
<p>

- Use list groups, and dynamically reorganize to keep actual downloads at the top of the page, and empty alerts at the bottom
![image](https://github.com/user-attachments/assets/9be4cf1a-623d-4b61-9b4a-362946d5685a)

</p>
</details>

2024-08-12 15:05 UTC, munnsmunns requested changes
Looks really good! Way better than before. I had one nitpicky suggestion, otherwise it's perfect

2024-08-12 15:05 UTC, munnsmunns commented on hawc/apps/assessment/templates/assessment/assessment_downloads.html
> +      <h6 class="mb-2 font-size-regular">{{assessment.get_rob_name_display|title}}</h6>
I think these titles are a bit too subtle. Maybe bold them?
![image](https://github.com/user-attachments/assets/7d0b976d-604d-4ef2-9288-15a9bc206cb6)

2024-08-14 18:15 UTC, munnsmunns approved these changes

2024-08-29 15:37 UTC, shapiromatron approved these changes
@caseyhans looks great! I was a little more aggressive than you and got rid of the sections if there's no data available to simplify the UI even more - what do you think?  Ok to merge pending any edits if you're ok w/ my changes.

2024-09-03 14:34 UTC, merged