create prisma ui
shapiromatron/hawc pull request #1072
Opened 2024-07-22 20:24 UTC by munnsmunns

2024-08-28 17:31 UTC, caseyhans requested changes
I have a couple minor comments to address, but overall this looks good! 

I do think these forms would benefit from adding flex col classes to the inputs (either the `input-group` div or wrapping each one in a new div). Most could be col-1, which would reduce the form size drastically. This would require more changes than my other comments and isn't necessary, but I think it's worth considering.

2024-08-28 17:31 UTC, caseyhans commented on frontend/summary/summaryForms/prisma/PrismaArrowsTable.js
> +                    <div className="border my-2 p-2 pb-3 edit-form-background ">
I would add a `pad-form` class to each edit row so that the inputs have a bit of separation

2024-08-28 17:31 UTC, caseyhans commented on frontend/summary/summaryForms/prisma/PrismaArrowsTable.js
> +                                label="width"
Capitalize this "width" label

2024-08-28 17:36 UTC, caseyhans commented on frontend/shared/components/EditableRowData.js
> +                        className="btn btn-sm btn-primary px-1"
add an mr-1 here

2024-09-05 14:25 UTC, shapiromatron approved these changes
LGTM! I made some minor edits below; see changes:

* 0de051697 use a random string key for all items
* 5062a5ef5 simplify read-only view
* 893b92423 revise base class
* d0712484f store edits

2024-09-05 14:27 UTC, shapiromatron commented
@caseyhans are you ok w/ the changes made? https://github.com/shapiromatron/hawc/pull/1072/commits/62825ffe40cf81b3f14e01ae746fa891ce01fe5a

2024-09-05 15:06 UTC, caseyhans approved these changes
LGTM!

2024-09-05 19:13 UTC, merged