Assessment tags apply UI
shapiromatron/hawc pull request #1085
Opened 2024-08-19 14:57 UTC by rabstejnek

2024-09-04 15:15 UTC, munnsmunns requested changes
Super impressive! Nice job on this one. I noticed you haven't added any tests/admin pages for the new models and views, which is my only suggestion right now. Nice job!

2024-09-04 15:15 UTC, munnsmunns commented on hawc/apps/assessment/urls.py
> +    path(
You should add these new views to the check_200 tests, and also add some example labels to the test fixture

2024-09-06 17:51 UTC, caseyhans commented on hawc/apps/assessment/migrations/0039_label_labeleditem_label_label_name.py
> +# Generated by Django 5.0.7 on 2024-08-30 21:46
I tweaked the label migration and removed this merge migration in favor of fewer files

2024-09-16 21:11 UTC, munnsmunns approved these changes

2024-09-27 16:33 UTC, merged