migrate data pivot to visual
shapiromatron/hawc pull request #1114
Opened 2024-09-28 03:08 UTC by shapiromatron

2025-02-14 16:41 UTC, caseyhans requested changes
This is a hefty PR and covers a lot of changes, great stuff. Most of this looks good. I noticed the LabeledItems are not migrating correctly, and the LabeledItemListView (and admin list view) are still trying to prefetch information for the old labels via the nonexistent DataPivot models. We could just exclude the old labels in the queryset manager (`.exclude(content_type__model__in=["datapivotquery", "datapivotupload"])`) or perhaps overwrite the prefetching to avoid these content types. Otherwise, looks good to me.

2025-02-14 22:46 UTC, rabstejnek approved these changes
Looks good! My only comment is that I don't see any use for the `dp_id` field being kept around; we should consider removing this field unless we want to keep it for posterity / have future need of it.

2025-02-18 22:29 UTC, rabstejnek commented on hawc/apps/summary/migrations/0059_move_data_pivot.py
> +    pd.DataFrame(data=mapping, columns="model|old_id|new_id".split("|")).to_csv(
Not sure if this excel was generated just for debugging purposes, but if you intend to keep this code here consider adding the generated excel file to `gitignore`.

2025-05-12 21:21 UTC, shapiromatron commented
@caseyhans great catch! I think it's ready for review one more time please; the relevant changes are in [e91188d](https://github.com/shapiromatron/hawc/pull/1114/commits/e91188d9eea01b296c0a0b956b166511f3e90c63)

2025-05-28 17:53 UTC, merged