Icf cpheapm71 72 add guidelines
shapiromatron/hawc pull request #1118
Opened 2024-10-11 17:32 UTC by ZindahFarhaICF

71
- Upload guideline table as json in the vocab app 'fixtures' folder.
- Update the experiment model to have a "guideline profile" (charfield) with validation from above guidelines.
72
- Create a GuidelineProfiles model and fixture with current hawc toxref endpoints

2024-10-11 18:46 UTC, ZindahFarhaICF commented on hawc/apps/vocab/constants.py
> +    TR = "triggered", "triggered"
Added type_checking for GuidelineProfile observation status, can be changed/removed as needed

2024-10-11 18:52 UTC, ZindahFarhaICF commented on scripts/client/load_guideline_profile.ipynb
> +    "\"\"\""
This notebook will probably be moved - mainly to demonstrate how guideline profiles were loaded (for review)

To load the model, I updated the endpoint ids in the given guideline_profiles spreadsheet to be the "endpoint target" (effect_subtype) id in the equivalent hawc vocab, and included the SQL logic for getting that here. Hopefully I didn't misunderstand the endpoints/goal here, but def let me know if I did!

2024-10-11 18:54 UTC, ZindahFarhaICF commented on hawc/apps/vocab/migrations/0009_guideline_profile.py
> +                ("endpoint_category", models.CharField(max_length=256)),
Guideline_profile_id is the primary key, and I kept the 3 vocab name fields that make up the endpoint. If they were mainly for my benefit to load in the vocab ids, I can remove them!

2025-01-23 16:29 UTC, shapiromatron requested changes
This looks good generally, unfortunately I think we wanted to add it to the bioassay-v2 schema, not the bioassy-v1 schema.

To do that, I think this PR may need to be closed and reworked and then submitted as new PR that should be merged into the `bioassay-v2` branch, not the main branch.

I think a lot of the code in the `hawc.apps.animal` will need to be modified and adapted to `hawc.apps.animalv2`. Hopefully that won't be too painful?

2025-01-23 16:31 UTC, shapiromatron commented on scripts/client/load_guideline_profile.ipynb
Is this script needed? What's the purpose of it, and when would we call it?

2025-02-10 21:10 UTC, closed without merging