replace custom .gif loader w/ font-awesome spinner
shapiromatron/hawc pull request #445
Opened 2021-05-27 14:52 UTC by shapiromatron

A long time ago in a galaxy far away when we started this project, there was no webpack or react and just jQuery. We had a custom loading gif that worked great for its time, but have since moved into a different more component-based world. This PR removes the old gif and uses a font-awesome spinner to be consistent with other loaders in HAWC.

<img width="194" alt="Screen Shot 2021-05-27 at 10 54 55 AM" src="https://user-images.githubusercontent.com/999952/119848680-01f65180-beda-11eb-8239-73069935ba5a.png">

URLs to check in dev db:
- visual: http://127.0.0.1:8000/summary/assessment/100000061/visuals/
- pubmed search: http://127.0.0.1:8000/lit/assessment/100500007/search/outbreak-salmonella-agona-europe/
- reference search: http://127.0.0.1:8000/lit/assessment/100000037/references/search/
- dp: http://127.0.0.1:8000/summary/data-pivot/assessment/100000037/pfbs-candidate-pods-subchronic-and-chronic-rfd/
- dp update: http://127.0.0.1:8000/summary/data-pivot/assessment/100000037/pfbs-candidate-pods-subchronic-and-chronic-rfd/update/

2021-06-01 02:59 UTC, rabstejnek requested changes
There are two function calls to `loader` instead of `loading`, but with that fixed it looks good to go!

2021-06-01 02:59 UTC, rabstejnek commented on frontend/summary/summaryForms/BaseVisualForm.js
> +            loading = HAWCUtils.loader();
Should be `HAWCUtils.loading()`

2021-06-01 02:59 UTC, rabstejnek commented on frontend/summary/summaryForms/BaseVisualForm.js
> +            loader = HAWCUtils.loader();
Should also be `HAWCUtils.loading()`

2021-06-01 18:35 UTC, shapiromatron commented on frontend/summary/summaryForms/BaseVisualForm.js
> +            loader = HAWCUtils.loader();
thanks, i'm glad you noticed this!

2021-06-03 15:31 UTC, rabstejnek approved these changes

2021-06-03 15:59 UTC, merged