Communication draft
shapiromatron/hawc pull request #528
Opened 2021-11-02 22:36 UTC by casey1173

accidentally pushed these changes to the DOIexport branch ... ignore that

2021-11-05 17:32 UTC, casey1173 commented
Adds a communication model for assessments and studies for internal, team-member only discussions about ongoing assessments.
### Assessment Communications
Project managers can update assessment communications under Assessment Editing in the Actions button.

![image](https://user-images.githubusercontent.com/42587248/140552623-e87ee012-561e-42b5-8b09-0fd135225564.png)


This opens a form for editing communications

![image](https://user-images.githubusercontent.com/42587248/140553113-5c1f4b4f-3d07-4de1-8a10-d5c0e84ed1f7.png)


Assessment communications are visible on the main assessment page, at the bottom. These are only visible for team members and higher.

![image](https://user-images.githubusercontent.com/42587248/140553001-02b2b404-be84-4db6-a866-5f3ccb4cba70.png)

### Study Communications
Team members can update study communications under Study editing, in the Actions button.

![image](https://user-images.githubusercontent.com/42587248/140553476-cb2e25c0-7571-405f-9e60-f9efad924599.png)


Study communications are visible on the main study page. Again, these communications are only visible for team members.

![image](https://user-images.githubusercontent.com/42587248/140553686-6d005ac2-657d-4ffe-ab23-12a947d25844.png)

2021-11-09 15:40 UTC, rabstejnek commented on hawc/apps/study/views.py
> +        import pdb
Remove this

2021-11-09 18:09 UTC, shapiromatron requested changes
Looking good! Please see the requested edits. The key ones are use f-strings when you can, and try to use the default class-lifecycle as much as possible with the views.

2021-11-09 18:09 UTC, shapiromatron commented on hawc/apps/assessment/views.py
> +    def post(self, request, *args, **kwargs):
try removing this and see if the complete lifecycle works; I don't think we need it.  The only thing you may need to change is to add a `get_success_url` method instead, and add the `reverse("assessment:detail", args=[kwargs["pk"]]`

2021-11-09 18:09 UTC, shapiromatron commented on hawc/apps/study/templates/study/study_detail.html
> +            {% if user_is_team_member_or_higher %}
dont use custom here, use `obj.editable`; remove from view

2021-11-09 18:09 UTC, shapiromatron commented on hawc/apps/study/views.py
> +    def post(self, request, *args, **kwargs):
again; try to remove the post as above

2021-11-09 18:09 UTC, shapiromatron commented on hawc/apps/study/views.py
> +                    name="Study " + str(study), url=reverse("study:detail", args=(study.id,))
use f string here too

2021-11-09 20:26 UTC, shapiromatron reviewed
Well done! Your changes look great. Really well done, now I think you know about 90% of the django + hawc view lifecycle.

Is it ok if I take this branch over now?  I'm going to make some changes that were out of scope of the original task; I'll ask you for a review when I'm complete?

2021-11-15 14:08 UTC, shapiromatron approved these changes
@casey1173 made a few changes to integrate with existing forms. Please review and let me know what you think.

Also, could you please it works for both create and update operations?

2021-11-15 22:56 UTC, merged