add swagger user interface `/api/swagger/`; admin-only
shapiromatron/hawc pull request #545
Opened 2021-11-23 03:52 UTC by shapiromatron

Add a browsable swagger user interface for admin and staff only f`{admin}/api/swagger/`:

<img width="1057" alt="Screen Shot 2021-11-22 at 10 52 30 PM" src="https://user-images.githubusercontent.com/999952/142968976-b1d532a9-4cd7-44b3-9b9c-2838cf2fcf92.png">

2021-12-01 22:11 UTC, rabstejnek requested changes
Its functional, but there are some styling problems that make part of the swagger ui hard to read:
<img width="875" alt="image" src="https://user-images.githubusercontent.com/46504563/144321689-75e7c2d5-5721-45f9-a852-0f8dd041172b.png">
This is from the `hawc.css` stylesheet. Maybe it would be better to extend "admin/base_site.html" instead of "base.html", kind of like the admin assessment size view does? (https://github.com/shapiromatron/hawc/blob/main/hawc/templates/admin/assessment-size.html)
This should make it so that `hawc.css` isn't imported, and may also look nicer thematically since this is also an admin only view.

2021-12-01 23:05 UTC, shapiromatron commented
> Its functional, but there are some styling problems that make part of the swagger ui hard to read: <img alt="image" width="875" src="https://user-images.githubusercontent.com/46504563/144321689-75e7c2d5-5721-45f9-a852-0f8dd041172b.png"> This is from the `hawc.css` stylesheet. Maybe it would be better to extend "admin/base_site.html" instead of "base.html", kind of like the admin assessment size view does? (https://github.com/shapiromatron/hawc/blob/main/hawc/templates/admin/assessment-size.html) This should make it so that `hawc.css` isn't imported, and may also look nicer thematically since this is also an admin only view.

I ilke the admin css idea; I'll give this a go...

2021-12-02 01:26 UTC, shapiromatron commented
@rabstejnek make required changes. I ended up getting rid of the custom css code, and switched over to `kbd` for the few places we needed it. 
<img width="905" alt="Screen Shot 2021-12-01 at 8 24 52 PM" src="https://user-images.githubusercontent.com/999952/144340630-3f5cddbd-1386-41a1-b8da-bdf339b813ba.png">

Using base admin failed when you have a dark-mode set on your computer, which I do, at least on my mac. [dark theme](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#admin-theming)

2021-12-02 02:13 UTC, rabstejnek approved these changes

2021-12-02 03:06 UTC, merged