json views to restful api
shapiromatron/hawc pull request #560
Opened 2021-12-16 21:38 UTC by casey1173

2021-12-27 14:21 UTC, casey1173 commented
https://github.com/shapiromatron/hawc/blob/397fb3c4d4d532364d2a9392dd58abbc6cb73d17/hawc/apps/lit/views.py#L252-L256
should this one be updated too?

2022-01-03 15:46 UTC, shapiromatron commented
@casey1173 If I recall that one's pretty complicated. It's fine to skip this one, it's a bit of a God (anti)pattern that I can investigate untangling.

2022-01-10 18:54 UTC, shapiromatron requested changes
Looking great so far. A few minor edits, mostly leveraging some of the built-in djago-rest framework instead of our custom code.

2022-01-10 18:54 UTC, shapiromatron commented on hawc/apps/lit/api.py
>          return self.get_paginated_response(serializer.data)
we might need to have two different endpoints `/references/` for pagination and `/references/all/` for no pagination

2022-01-20 16:52 UTC, shapiromatron approved these changes
Looks great. I went overboard and kept fixing other things and legacy views that I saw when I reviewed your code.    The end result is i think we have a much more readable code-base and more standardization on where things should go.

Nice job!

2022-01-20 16:54 UTC, merged