Build start of epi v2 form views
shapiromatron/hawc pull request #583
Opened 2022-01-26 20:13 UTC by munnsmunns

Create a basic django form for the Design model in epi v2

2022-01-27 22:21 UTC, shapiromatron requested changes
looking excellent, minor comments

2022-01-27 22:21 UTC, shapiromatron commented on hawc/apps/epiv2/urls.py
> +    path("study/<int:pk>/design/create/", views.DesignCreate.as_view(), name="des_create",),
use the full name for `name="design_create"`; here and elsewhere

2022-01-27 22:21 UTC, shapiromatron commented on hawc/apps/epiv2/templates/epiv2/design_detail.html
> +<div id="objContainer"></div>
delete objContainer for now; we can add later when we have some javascript that builds this

2022-01-27 22:21 UTC, shapiromatron commented on hawc/main/urls.py
> +    path("epiv2/", include("hawc.apps.epiv2.urls")),
rename to `epidemiology` for our public views?

2022-01-27 22:21 UTC, shapiromatron commented on hawc/apps/epiv2/templates/epiv2/design_detail.html
> +        <a class="dropdown-item" href="{% url 'epiv2:des_delete' pk=object.pk %}">Delete</a>
remove the `pk=` for consistency with the previous line

2022-01-27 22:21 UTC, shapiromatron commented on hawc/apps/epiv2/templates/epiv2/design_detail.html
> +<h1 class="d-inline-block">{{object.name}}</h1>
change to h2; there's a PR in he works that will change all the h1 to h2

2022-01-27 22:21 UTC, shapiromatron commented on hawc/apps/study/templates/study/study_detail.html
> +              <a class="dropdown-item" href="{% url 'epiv2:des_create' object.pk %}">Create new study population</a>
i would change this slightly. i'd put the epi_version if statement nested in the object.epi, and just switch the a links instead of the whole div

2022-01-28 15:27 UTC, munnsmunns commented
@shapiromatron good to merge now?

2022-01-31 15:20 UTC, merged