Add framework for Assessment values
shapiromatron/hawc pull request #674
Opened 2022-07-27 15:17 UTC by munnsmunns

Creates a simple schema and adds basic CRUD operations for Assessment Values.

2022-07-27 16:13 UTC, shapiromatron requested changes
This is a great start. Very minimal, just what we need to get started I think.

2022-07-27 16:13 UTC, shapiromatron commented on hawc/apps/assessment/models.py
> +    assessment = models.ForeignKey(Assessment, models.CASCADE, related_name="values_list")
maybe just `values` instead?

2022-07-27 16:13 UTC, shapiromatron commented on hawc/apps/assessment/views.py
> +        context["assessment_values"] = context["object"].values_list.all()
i dont think this is needed; you can just do this directly in the template

2022-07-27 16:13 UTC, shapiromatron commented on hawc/apps/assessment/templates/assessment/assessmentvalues_detail.html
> +{% block content %}
For now, can we revise this template to look more like the /study/:id template?

That is, there will be an Actions button in the top right to update/delete, and then the attributes of the value will be in a table, where each row is an attribute.

That way it'll be easier to add new values

2022-07-27 16:13 UTC, shapiromatron commented on hawc/apps/assessment/templates/assessment/_assessmentvalue_list.html
> +            <td>
we need to selectively show/hide that entire column depending on permission - if you can't edit, we shouldn't show the thead either

2022-07-27 16:20 UTC, munnsmunns commented
@shapiromatron any idea what's going on in the failing tests? It's not clear to me why they're connected with this new model

2022-07-27 16:24 UTC, shapiromatron commented
> @shapiromatron any idea what's going on in the failing tests? It's not clear to me why they're connected with this new model

Agree; this doesnt look related to your work.

Yes; I think we don't have an explicit order on some of these queryset results, so sometimes we get ordering differences. Looping in @rabstejnek in case he has ideas; I think some of this were changes in related work

2022-07-28 19:18 UTC, shapiromatron requested changes
A few more minor comments regarding the admin and reversion registration

2022-07-28 19:18 UTC, shapiromatron commented on hawc/apps/assessment/admin.py
> +class ValuesAdmin(admin.ModelAdmin):
might be good to select_related the assessment too since as it's currently designed it will need to query each assessment in the table as well

2022-07-28 19:18 UTC, shapiromatron commented on hawc/apps/assessment/models.py
> +reversion.register(Assessment, follow=["values"])
instead of adding this model to follow, add another row to just register this one by itself.

2022-08-09 22:58 UTC, shapiromatron commented on hawc/apps/assessment/models.py
> +    # TODO: figure out how to avoid circular imports/models aren't loaded yet
https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.ForeignKey

```python
class Car(models.Model):
    manufacturer = models.ForeignKey(
        'production.Manufacturer',
        on_delete=models.CASCADE,
    )
```

2022-08-09 23:00 UTC, shapiromatron commented on hawc/apps/hawc_admin/serializers.py
> +class ValuesExportOptions:
i'd move this to the `assesssment.exports`; there are other common patterns you can check that follow this

2022-08-09 23:01 UTC, shapiromatron commented on hawc/apps/hawc_admin/api.py
> +        detail=False, renderer_classes=PandasRenderers, throttle_classes=(FivePerMinuteThrottle,)
no need for a custom throttle here

2022-08-22 18:21 UTC, munnsmunns commented on setup.cfg
> +    hawc = hawc:manage
dependency issue with celery - requires setuptools<59.7

2022-09-23 20:25 UTC, shapiromatron commented on hawc/apps/hawc_admin/api.py
> +from hawc.apps.assessment.models import Values
keep these relative imports, consistent with the rest of hawc, here and elsewhere

2022-09-29 15:21 UTC, shapiromatron approved these changes
LGTM - please take a review and merge this in. Thanks!

2022-09-29 19:22 UTC, munnsmunns commented
> LGTM - please take a review and merge this in. Thanks!

Everything looks good! Nothing to say on the changes, the code is clear and everything works as it should.

2022-09-29 19:22 UTC, merged