interactive generic summary tables
shapiromatron/hawc pull request #786
Opened 2023-02-17 04:02 UTC by shapiromatron

Add optional [datatables.net](https://datatables.net/) interactive to generic tables.

![Screenshot 2023-02-16 at 11 02 01 PM](https://user-images.githubusercontent.com/999952/219546396-c87b393b-ddd7-4135-82e8-d340a3707403.jpg)

(data generated using [Faker](https://pypi.org/project/Faker/)).

2023-02-24 22:34 UTC, rabstejnek requested changes
I noticed some weirdness when sorting by columns on a generic summary table:

<img width="102" alt="image" src="https://user-images.githubusercontent.com/46504563/221304639-5bce6673-5acc-4837-8c59-41b09c4fde48.png">

Also on the heatmap visual, if you fetch one dataset and then fetch a different kind of dataset, you get an error and the page breaks:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/46504563/221307491-edd6debb-edf7-4f77-8a83-310653fbda4f.png">

Besides that it looks good! We should try to address these errors, but after that its good to merge.

2023-02-24 23:00 UTC, rabstejnek commented
I believe the sorting problem is because the user copy/pasted HTML into the example I'm looking at. I tried explicitly setting the [column types](https://datatables.net/reference/option/columns.type) to `html` and it was still an issue, so I'm guessing there's nothing we can do about sorting weird HTML fragments that were copied in by a user.

2023-02-27 03:29 UTC, shapiromatron commented
> I noticed some weirdness when sorting by columns on a generic summary table:
> 
> <img alt="image" width="102" src="https://user-images.githubusercontent.com/46504563/221304639-5bce6673-5acc-4837-8c59-41b09c4fde48.png">
> 
> Also on the heatmap visual, if you fetch one dataset and then fetch a different kind of dataset, you get an error and the page breaks:
> 
> <img alt="image" width="338" src="https://user-images.githubusercontent.com/46504563/221307491-edd6debb-edf7-4f77-8a83-310653fbda4f.png">
> 
> Besides that it looks good! We should try to address these errors, but after that its good to merge.

Fixed the issue w/ the heatmap visual - ok to merge?

2023-02-27 05:09 UTC, rabstejnek approved these changes

2023-02-27 17:16 UTC, merged