replaced FilterForms with InlineFilterForms
shapiromatron/hawc pull request #838
Opened 2023-05-31 20:11 UTC by dannypeterson

2023-06-14 17:19 UTC, casey1173 requested changes
Lots of good stuff here! I've given some feedback, feel free to message me or reply if you've got any questions about specifics.

Most of my feedback is either:
1. Removing duplicate fields added to the filtersets
2. Providing clearer names for new fields

I left most of my feedback on the fields themselves, but if you change a name/remove a field you'll have to update the 'fields' Filterset attribute and the main_field/appended_fields too.

2023-06-14 17:19 UTC, casey1173 commented on hawc/apps/mgmt/filterset.py
> -        lookup_expr="icontains", field_name="study__short_citation", label="Study name"
I like this change! Let's change 'search' to a more descriptive name though, like "study_assessment_name"

2023-06-14 17:19 UTC, casey1173 commented on hawc/apps/study/filterset.py
> +        help_text="Filter by citation (authors, year, title, etc) or datatbase identifier (PubMed ID, DOI, HERO ID, etc.)",
I like these combo fields!
Again, try to name them more descriptively (maybe "citation_or_id").
You've got a typo in the help text here (datatbase), but I'd get rid of that word entirely (Filter by citation (...) or identifier (...).

2023-06-14 17:19 UTC, casey1173 commented on hawc/apps/study/filterset.py
> -        form.fields["assigned_user"].queryset = self.assessment.pms_and_team_users()
I think you still need this; otherwise the field will show all HAWC users

2023-06-14 17:19 UTC, casey1173 commented on hawc/apps/study/filterset.py
> -            form.fields.pop("published")
We need this logic too. You could move it to get_filterset_form_kwargs as a dynamic_fields argument, but it can probably stay here if it works as is

2023-07-24 20:05 UTC, casey1173 approved these changes

2023-07-25 13:55 UTC, shapiromatron commented
Instead of a "default ordering", what if we always set a ordering, and update the choices to make the text a little shorter?:

```python
order_by = df.OrderingFilter(
        initial="-year",
        empty_label=None,
        fields=(
            ("authors", "authors"),
            ("year", "year"),
        ),
        choices=(
            ("authors", "↑ authors"),
            ("-authors", "↓ authors"),
            ("year", "↑ year"),
            ("-year", "↓ year"),
        ),
        help_text="How results will be ordered",
    )
```

![image](https://github.com/shapiromatron/hawc/assets/999952/178be31e-33a7-4fd7-902a-f5f8163a84d1)

![image](https://github.com/shapiromatron/hawc/assets/999952/257dc668-8a89-4e9f-8b1d-379088610c8a)


I can make the changes @casey1173, just curious if this makes the UI clearer

2023-07-25 13:59 UTC, casey1173 commented
> Instead of a "default ordering", what if we always set a ordering, and update the choices to make the text a little shorter?:
> 
> ```python
> order_by = df.OrderingFilter(
>         initial="-year",
>         empty_label=None,
>         fields=(
>             ("authors", "authors"),
>             ("year", "year"),
>         ),
>         choices=(
>             ("authors", "↑ authors"),
>             ("-authors", "↓ authors"),
>             ("year", "↑ year"),
>             ("-year", "↓ year"),
>         ),
>         help_text="How results will be ordered",
>     )
> ```
> 
> ![image](https://user-images.githubusercontent.com/999952/255922088-178be31e-33a7-4fd7-902a-f5f8163a84d1.png)
> 
> ![image](https://user-images.githubusercontent.com/999952/255922221-257dc668-8a89-4e9f-8b1d-379088610c8a.png)
> 
> I can make the changes @casey1173, just curious if this makes the UI clearer

fine by me @shapiromatron !!

2023-07-25 16:36 UTC, shapiromatron approved these changes
Looks great, I think our users will really like this change after they get used to it!

@casey1173 I made some minor mostly textual edits; please make sure you're ok with my changes (I'd look at the 3 commits I added insteadof the whole PR) - and if you're ok with change, ok to merge!

2023-07-25 17:03 UTC, merged