added dich % change calc
shapiromatron/hawc pull request #909
Opened 2023-09-28 18:43 UTC by dannypeterson

2023-09-28 20:32 UTC, shapiromatron requested changes
one minor change to how change is calculated; we have to normalize to fraction incidence instead of raw unnormalized counts

2023-09-28 20:32 UTC, shapiromatron commented on hawc/apps/animal/models.py
> +                    mean = ((incidence - control_incidence) / n_1) * 100
i think this need to be ((i1/n1)-(i0/n0))/(i0/n0), where i is incidence and n is num animals

2023-09-29 15:06 UTC, dannypeterson commented
![percent change calc](https://github.com/shapiromatron/hawc/assets/113325602/1278df81-3997-474c-a5e3-9d3028a4e7cb)
Updated the calc to ((i1/n1)-(i0/n0))/(i0/n0), but the calculations seem weird... (0.7 - 0.1) / (0.1) = 0.6/0.1 = 6 so not sure why we are getting a 5.99 float. Also shouldnt the result be 0.6 instead bc we multiply by 100 for % change

2023-09-29 16:47 UTC, shapiromatron commented
> ![percent change calc](https://user-images.githubusercontent.com/113325602/271643215-1278df81-3997-474c-a5e3-9d3028a4e7cb.png) Updated the calc to ((i1/n1)-(i0/n0))/(i0/n0), but the calculations seem weird... (0.7 - 0.1) / (0.1) = 0.6/0.1 = 6 so not sure why we are getting a 5.99 float. Also shouldnt the result be 0.6 instead bc we multiply by 100 for % change

That seems correct! I think it's a 600% percent chagne relative to control

2023-09-29 17:35 UTC, shapiromatron commented on hawc/apps/animal/models.py
> +                    mean = ((i_1 / n_1) - (i_0 / n_0)) / (i_0 / n_0) * 100
looks correct! you can see we do the same on line 1219 `  mean = (mu_2 - mu_1) / mu_1 * 100.0`

2023-09-29 17:50 UTC, shapiromatron approved these changes

2023-09-29 18:18 UTC, merged