Improve handling of published/unpublished data in downloads
shapiromatron/hawc pull request #956
Opened 2023-11-29 19:58 UTC by munnsmunns

2023-12-04 14:50 UTC, shapiromatron commented on hawc/apps/assessment/templates/assessment/assessment_downloads.html
> +        {% url 'animal:api:assessment-full-export' assessment.pk as the_url %}
Can you make a component for this little collection of spans and links?

```
{% include 'assessment/components/foo.html' with url=the_url %}
```

Something like that, but with a better name :)

2023-12-05 23:09 UTC, shapiromatron reviewed
looking good - a few minor updates to the templates, but code looks good

2023-12-05 23:09 UTC, shapiromatron commented on hawc/apps/assessment/templates/assessment/assessment_downloads.html
> +<p class='form-text text-muted mb-3'>
only all added content if team member or higher?

2023-12-05 23:09 UTC, shapiromatron commented on hawc/apps/assessment/templates/assessment/assessment_downloads.html
> +        {% url 'animal:api:assessment-full-export' assessment.pk as the_url %}
Can you make a component for this little collection of spans and links?

```
{% include 'assessment/components/foo.html' with url=the_url %}
```

Something like that, but with a better name :)

2023-12-05 23:09 UTC, shapiromatron commented on hawc/apps/common/api/utils.py
> +    can_edit = assessment.user_is_team_member_or_higher(request.user)
good catch

2023-12-05 23:09 UTC, shapiromatron commented on tests/hawc/apps/epi/test_api.py
> +    def _test_flat_export(
this is a nice refactoring

2023-12-07 17:42 UTC, munnsmunns commented
@shapiromatron should any of the lit, risk of bias, in vitro, or epi-meta exports have the unpublished filter added?

2023-12-07 18:16 UTC, shapiromatron commented
> @shapiromatron should any of the lit, risk of bias, in vitro, or epi-meta exports have the unpublished filter added?

Yes, we'll need it for invitro, epimeta, and riskofbias.  We wont for lit.  I think invitro and epimeta may not be to difficult and will be similar to epi/epiv2, but riskofbias may be really different. I can help if needed.

2024-01-05 02:25 UTC, shapiromatron requested changes
Looking great, a few mostly minor changes requested; it should be ready after those are in. I really like the UI change you made; it's much simpler and more intuitive than what I did.

2024-01-05 02:25 UTC, shapiromatron commented on hawc/apps/riskofbias/api.py
>          exporter = exports.RiskOfBiasCompleteFlat(
The published_only variable should be passed in here and handled in the class init.  It should be available in the kwargs dictionary on the instance.

2024-01-05 02:25 UTC, shapiromatron commented on hawc/apps/riskofbias/api.py
> +        exporter.published_only = published_only
Same comment as below; pass in via the init

2024-01-10 21:54 UTC, shapiromatron approved these changes
Looks great! I made two very minor edits; if you're ok w/ changes, ok to merge.

* 4e2d5b5f whitespace edits (12 seconds ago)
* 018010a9 only add the unpublished flag if the checkbox exists (57 minutes ago)

2024-01-11 14:37 UTC, merged